language: python
python:
  - '2.7'
  - 'pypy'
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - python setup.py test
  - cd docs && make html
env:
  global:
    - secure: "NosCss+2t7AtZr11+fzzzZ6LECfB+9LT6pGAwsUkXxr88WtoTDMpwgRnCCIzIKpU8ffGZkWlA0H8jAQmX2b+nCt1A9MCwhRkYUC3XWzBWDCYz/o2HzvReWyTcogAF3NbIrSDIRPa87kVjtQLpJ959fLuHZM1p1onH7AV/Oqw5HQ="
    - secure: "Z0PwPA7bkkdVtcX3j7O6AOCdJjvB18AVCLg90h9cL4KlBZ86w0OyvpFnzPvgBjCF0LowaajILdtNQhgFMqrqhdzemj+R2dtjs9jNigcqW0cMkZZT2CpplgcoIsCOv05S99iDAnZPgO7SZggkkbYHKKs2pecmps3au4PxhboqsGg="
